% Diagnoise noise for W-band radar with hourly noise power 
% histogram file noise_dBmW.dat, generated by proc_wband_hourly_noise.m
%
% VOCALS 2008 :: 2009-October-19 :: Simon de Szoeke

run('../read_parameters')

% open data files
fidnoise=fopen([way_proc_data_wband 'noise_dBmW.dat'],'r','ieee-le');
fidnoisetime=fopen([way_proc_data_wband 'noise_time.dat'],'r','ieee-le');

binrucnoise=-122:.02:-100;
time=fread(fidnoisetime,'uint32');
nb=length(binrucnoise);

A=fread(fidnoise,'uint16');
nt=length(A)/nb;

noiseun=reshape(A,[nb,nt]);
%normalize
s=sum(noiseun,1);
m=max(noiseun,1);
noise=noiseun./repmat(s,[size(noiseun,1) 1]);

pcolor(time,binrucnoise,log10(noise))
shading flat
colorbar

semilogy(repmat(binrucnoise',[1,nt])-0.01+0.02*rand(nb,nt),...
    noise.*(1+5e-2*(-1+2*rand(nb,nt))),'.','markersize',1)
ylabel('frequency')
xlabel('range-UNcorrected power (dBmW)')
print('-depsc2',[way_proc_images_wband 'noise_edge.eps'])